
<!-- Begin MailChimp Signup Form -->
<!--
<div id="mc_embed_signup">
<form action="http://dvsdev.us3.list-manage.com/subscribe/post?u=c7599305560279abb0f548e20&amp;id=903bbfa2c7" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
		
		<!-- ########## First Name ########## 
		<p class="mc-field-group">
			<label for="mce-FNAME" class="hiddenLabel">First Name </label>
			<input type="text" value="First Name" name="FNAME" class="" id="mce-FNAME">
		</p>
		<p class="mc-field-group"> 
			<!-- ########## Last Name ########## 
			<label for="mce-LNAME" class="hiddenLabel">Last Name </label>
			<input type="text" value="Last Name" name="LNAME" class="" id="mce-LNAME" />
		</p>-->
		
		<!-- ########## Email Address ##########
		<p  class="mc-field-group">
			<label for="mce-EMAIL" class="hiddenLabel">Email Address <span class="asterisk">*</span> </label>
			<input type="email" value="Email Address" name="EMAIL" class="required email" id="mce-EMAIL" />
		</p>
		<div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div> -->
		<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups
		<div style="position: absolute; left: -5000px;">
			<input type="text" name="b_c7599305560279abb0f548e20_c101510826" value="">
		</div>
		<p>
			<button class="button" type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe">Subscribe</button>
		</p>
	</form>
</div>-->
