<form method="post" action="http://www.aweber.com/scripts/addlead.pl" id="newsletterForm" accept-charset="UTF-8" novalidate="novalidate">
            <div style="display: none;">
            	<input type="hidden" name="meta_web_form_id" value="1534992630">
            	<input type="hidden" name="meta_split_id" value="">
            	<input type="hidden" name="listname" value="dvscm-1">
            	<input type="hidden" name="redirect" value="http://www.dvscampmarketing.com/confirm-your-request.html" id="redirect_56b51dd75b907b601ba3af7a540e54ab">
            	
            	<input type="hidden" name="meta_adtracking" value="dvscm">
            	<input type="hidden" name="meta_message" value="1">
            	<input type="hidden" name="meta_required" value="name,email">
            	<input type="hidden" name="meta_forward_vars" value="1">
            	<input type="hidden" name="meta_tooltip" value="name||Your first name,,email||Your email address">
            </div>
            
            <p class="firstNewsletterForm">
              <input id="awf_field-34974341" class="input-text validate[required,funcCall[checkNAME]]" value="Your First Name" name="name" type="text" style="color: rgb(142, 141, 141);">
            </p>
            <p>
              <input id="awf_field-34974342" class="input-text validate[required,custom[email]]" value="Your Email" name="email" type="text" style="color: rgb(142, 141, 141);">
            </p>
            <p>
              <button class="button" id="af-submit-image-1534992630">Subscribe</button>
            </p>
            </form>