			</div>
			<!--end contentRight-->
			<div class="contentLeft">
				<div class="boxWrapperInner">
					<div class="videoBoxInner"><a href="#"> <img  id="videoBackgroundInner" src="<?= $config->urls->templates?>images/videoBackground.png" alt="videobg"/> <img  id="movieFilmInner" src="<?= $config->urls->templates?>images/movieFilm.png" alt="movieFilm"/> <span>Watch Our Video</span></a>
					</div>
					<!--end videoBoxInner-->
					
					<ul class="imageBoxWrapperInner">
						<li class="imageBoxleftInner"> <a href="#"><img  id="campDayInner" src="<?= $config->urls->templates?>images/campDayInner.png" alt="campDay"/> <span>See a Typical Day at Camp</span> </a>
						</li>
						<!--end imageBoxleftInner-->
						
						<li class="imageBoxcenterInner"> <a href="#"><img  id="interactiveMapInner" src="<?= $config->urls->templates?>images/interactiveMapInner.png" alt="interactiveMap"/><span> View our Interactive Map</span></a>
						</li>
						<!--end imageBoxcenterInner-->
					
						<li class="imageBoxrightInner"><a href="#"><img  id="photoGalleryInner" src="<?= $config->urls->templates?>images/photoGaleryInner.png" alt="photogallery"/> <span>View our Photo Gallery</span> </a>
						</li>					
						<!--end imageBoxrightInner-->
					</ul>
					<!--end imageBoxWrapperInner--> 
				</div>
				<!--end boxWrapperInner--> 
			</div>
			<!--end contentLeft--> 
		
		</div>
		<!--end contentTwoCollumns--> 